// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// Placeholder values — replace with the values produced by:
//
//     dart pub global activate flutterfire_cli
//     flutterfire configure
//
// (run those commands inside the project root after you create a Firebase
// project at https://console.firebase.google.com and register a Web app +
// an Android app for the same project).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default Firebase options for the NoteHere project.
///
/// Edit each `apiKey`, `projectId` and `appId` to match the values
/// printed by `flutterfire configure`. Keep the structure intact so
/// `DefaultFirebaseOptions.currentPlatform` continues to work on every
/// supported platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        // Web fallback for desktop while desktop Firebase support is opt-in.
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY6zJML1x1DTJAJeIoiyuJ7JTYkuiLa5o',
    appId: '1:1094319333389:web:794647c7256fe5d0e07544',
    messagingSenderId: '1094319333389',
    projectId: 'notehere-test',
    authDomain: 'notehere-test.firebaseapp.com',
    storageBucket: 'notehere-test.firebasestorage.app',
    measurementId: 'G-2TCX8F66S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdhHRT0coPD0WFHFH0Xj3yrbORR8PoPmk',
    appId: '1:1094319333389:android:e099ffcd67eb7fbfe07544',
    messagingSenderId: '1094319333389',
    projectId: 'notehere-test',
    storageBucket: 'notehere-test.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCclxevnCNi0losbtbsZ6wiRUiu0OrfeSY',
    appId: '1:1094319333389:ios:77925e271ff678bce07544',
    messagingSenderId: '1094319333389',
    projectId: 'notehere-test',
    storageBucket: 'notehere-test.firebasestorage.app',
    iosBundleId: 'com.notehere.noteHere',
  );
}
